//SOLO DEBE TENER METODOS PARA MOSTRAR INFORMACION - MENU - ETC

//METODOS PARA LA ENTRADA DEL USUARIO
//FORMATEAR HISTORIAL
// PANTALLA PRINCIPAL CON VARIOS PARAMETROS - NOMBRE TIENDA - VENDEDOR
// RESTO DE PANTALLAS CON PARAMETROS - SIEMPRE INVOCADAS DESDE EL PRESENTADOR
// PARAMETROS TAMBIEN PASADOS POR PRESENADOR

// INVOCA AL PRESENTADOR CUANDO EL USUARIO INGRESA UNA OPCION.